title = "Dataset configurator"

[dataset]
main_path = "/home/marilia/Documents/Datasets/HumanPatterns/DogWalking/Marilia/AfternoonWalk/Right Forearm/SM-G925F_359521064204367/2019-04-09_18-41-23/"

[ontology]
Accelerometer=[0,1,2,3]
Gyroscope=[0,1,2,3]
Magnetometer=[0,3]

[parameters]
time_unit = 1e9  # seconds
resample_rate = 30  # resample sampling frequency
window_size = 100 # number of points
overlap = 0 # varies between 0 and 1

